<a href="https://colab.research.google.com/github/Desmyk/PYDATA/blob/main/Numpytest1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import numpy package under name np

import numpy as np

In [5]:
# print numpy version and config

print(np.show_config)
print(np.__version__)

<function show at 0x793616edc820>
1.25.2


In [7]:
# create a null vector of size 10

X = np.zeros(10)
print(X)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
# find memory size of any array

x = np.array([20,30,20])
print(x.size) # size of array
print(x.itemsize) # size of element in bytes

3
8


In [51]:
# get the documentation of the numpy add function from the command line

np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [20]:
# Create a null vector of size 10 but the fifth value which is 1

X = np.zeros(10)
X[4] = 1
print(X)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [26]:
# vector with values ranging from 10 to 49

X = np.arange(10,50)
print(X)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [29]:
# reverse a vector (1st element to last)

X = np.arange(50)
X = X[::-1]
print(X)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [44]:
# create a 3 x 3 matrix with values ranging from 0 to 8

X = np.arange(9).reshape(3, 3)
print(X)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [48]:
# find indices of non-zero elements from [1,2,0,0,4,0]

X = np.nonzero([1,2,0,0,4,0])
print(X)

(array([0, 1, 4]),)


In [30]:
# create a 3 x 3 identity matrix

X = np.eye(3)
print(X)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
# a 3 x 3 x 3 array with random values

X = np.random.random([3,3,3])
print(X)

[[[0.80679525 0.02741053 0.84576922]
  [0.85616307 0.53203386 0.79016555]
  [0.40909793 0.31416389 0.1510655 ]]

 [[0.38256203 0.90323927 0.49235712]
  [0.90259517 0.63640648 0.51789866]
  [0.95354573 0.09654917 0.42947864]]

 [[0.31139344 0.10456579 0.53944884]
  [0.07074645 0.83842049 0.10412874]
  [0.08090417 0.39737469 0.83332752]]]


In [34]:
# a 10 x 10 array with random values, find min and max values

X = np.random.random([10,10])
print(X)

[[0.31781051 0.60614724 0.88078865 0.88121223 0.82194366 0.96607016
  0.08366673 0.93726635 0.33540391 0.41778428]
 [0.14156376 0.78710481 0.06963046 0.73758693 0.27968413 0.84366417
  0.19879765 0.84367029 0.06661681 0.2383416 ]
 [0.2564442  0.35195591 0.17552954 0.67084269 0.0607959  0.58139388
  0.39003612 0.42339355 0.06210125 0.62551327]
 [0.09186208 0.39419968 0.69504839 0.73943852 0.73254611 0.2685858
  0.13124228 0.93478078 0.58376231 0.98334416]
 [0.25362952 0.14378704 0.00488529 0.83869    0.3651602  0.15743652
  0.66172571 0.88950967 0.69019199 0.78688915]
 [0.38987606 0.42497806 0.00548959 0.12902092 0.53705745 0.97862946
  0.1825421  0.34709742 0.05429613 0.50007594]
 [0.85227369 0.91257801 0.38336741 0.16703722 0.85486216 0.25362272
  0.05250762 0.0934618  0.32226492 0.39825817]
 [0.63748489 0.49303328 0.35067315 0.22009735 0.54639608 0.07434945
  0.76016613 0.27890339 0.85971143 0.09141275]
 [0.19144279 0.53869368 0.00566195 0.25300957 0.27540217 0.86577642
  0.53571934 

In [37]:
# a random vector size of 30, find mean

X = np.random.random(30)
m = X.mean()
#print(X)
print(m)

0.5579597086633861


In [46]:
# a 2D array with 1 on the border and 0 inside

X = np.ones([10,10])
X[1:-1,1:-1]=0
print(X)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
