<a href="https://colab.research.google.com/github/Desmyk/PYDATA/blob/main/numpytest3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
# How to ignore all numpy warnings (not recommended)

# Suppress Warnings
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [2]:
# Is the following expressions true?

np.sqrt(-1) == np.emath.sqrt(-1)


<ipython-input-2-4cdd710269fc>:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [5]:
# How to get the dates of yesterday, today and tomorrow?

yesterday = np.datetime64('today', 'D')- np.timedelta64(1, 'D')
print("Yestraday: ", yesterday)

today = np.datetime64('today', 'D')
print("Today: ", today)

tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ", tomorrow)


Yestraday:  2024-03-26
Today:  2024-03-27
Tomorrow:  2024-03-28


In [8]:
# How to get all the dates corresponding to the month of July 2016?

print("July, 2016")
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

July, 2016
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [9]:
# How to compute ((A+B)*(-A/2)) in place (without copy)?

A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


array([-1.5, -1.5, -1.5])

In [10]:
# Extract the integer part of a random array of positive numbers using 4 different methods

X = np.random.uniform(0,10,10)

print(X - X%1)
print(X // 1)
print(np.floor(X))
print(X.astype(int))
print(np.trunc(X))

[1. 3. 5. 4. 8. 8. 1. 2. 3. 8.]
[1. 3. 5. 4. 8. 8. 1. 2. 3. 8.]
[1. 3. 5. 4. 8. 8. 1. 2. 3. 8.]
[1 3 5 4 8 8 1 2 3 8]
[1. 3. 5. 4. 8. 8. 1. 2. 3. 8.]


In [11]:
# Create a 5x5 matrix with row values ranging from 0 to 4

X = np.zeros((5,5))
X += np.arange(5)
print(X)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [12]:
# Consider a generator function that generates 10 integers and use it to build an array

def generate():
    for x in range(10):
        yield x
X = np.fromiter(generate(),dtype=float,count=-1)
print(X)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [13]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded

X = np.linspace(0,1,11,endpoint=False)[1:]
print(X)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [14]:
# Create a random vector of size 10 and sort it

X = np.random.random(10)
X.sort()
print(X)

[0.05056861 0.06520556 0.08890574 0.1172409  0.41879442 0.44910604
 0.51403051 0.55806522 0.65956251 0.68628359]


In [15]:
# How to sum a small array faster than np.sum?

X = np.arange(10)
np.add.reduce(X)

45

In [26]:
# Consider two random array A and B, check if they are equal

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.array_equal(A,B)
print(equal)

False


In [27]:
# Make an array immutable (read-only)

X = np.zeros(10)
X.flags.writeable = False
X[0] = 1

ValueError: assignment destination is read-only

In [28]:
# Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.34711915 0.71624513 0.97915052 0.6263554  0.60110275 0.75010846
 0.92315054 0.58976721 0.2560027  1.05283026]
[0.9294006  1.41923412 0.77640203 1.55297157 0.18468639 0.25760593
 0.84177957 1.22164256 0.92298004 0.99604654]


In [29]:
# Create random vector of size 10 and replace the maximum value by 0

X = np.random.random(10)
X[X.argmax()] = 0
print(X)

[0.62896148 0.46255649 0.53733136 0.26420483 0.3047531  0.18790626
 0.5944851  0.12880981 0.         0.52455674]
