<a href="https://colab.research.google.com/github/Desmyk/PYDATA/blob/main/weeklynumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Find the nearest value from a given value in an array

Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)


0.5688028196475271


In [3]:
# Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator

A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])



[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [4]:
# Create an array class that has a name attribute

class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)


range_10


In [6]:
# Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)

Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
np.add.at(Z, I, 1)
print(Z)


[7. 9. 3. 1. 5. 9. 7. 5. 1. 3.]


In [7]:
# How to accumulate elements of a vector (X) to an array (F) based on an index list (I)

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)


[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [8]:
# Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)


64


In [9]:
# Considering a four dimensions array, how to get sum over the last two axis at once

A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[47 59 46 52]
 [64 50 50 49]
 [62 39 62 62]]


In [10]:
# Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.39279785 0.49658254 0.52540522 0.41359128 0.48920027 0.52966641
 0.56045731 0.46876747 0.43058281 0.50352998]


In [11]:
# How to get the diagonal of a dot product

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))

array([0.90088937, 0.83320071, 1.59296877, 0.58191481, 1.44138929])

In [12]:
# Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value

Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [13]:
# Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions

A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [14]:
# How to swap two rows of an array

A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)


[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [15]:
# Consider a set of 10 triplets describing 10 triangles (with shared vertices),
# find the set of unique line segments composing all the triangles

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0,  4) ( 0, 88) ( 3, 51) ( 3, 90) ( 4, 88) ( 5, 15) ( 5, 26) ( 8, 57)
 ( 8, 59) ( 9, 61) ( 9, 98) (12, 67) (12, 81) (15, 26) (21, 38) (21, 57)
 (23, 56) (23, 76) (34, 38) (34, 86) (38, 57) (38, 86) (47, 52) (47, 94)
 (51, 90) (52, 94) (56, 76) (57, 59) (61, 98) (67, 81)]


In [16]:
# Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C

C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [18]:
# How to compute averages using a sliding window over an array

from numpy.lib.stride_tricks import sliding_window_view
Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [19]:
# Consider a one-dimensional array Z,
# build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and
# each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])


Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))


[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [20]:
# How to negate a boolean, or to change the sign of a float inplace

Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)


array([ 0.40286996,  0.5551137 , -0.2452888 ,  0.50842393, -0.15981109,
        0.99911603, -0.03886134,  0.63908437,  0.73563937,  0.43289847,
        0.69699055, -0.5562326 , -0.22185129, -0.77901185, -0.88529598,
        0.7921135 , -0.73504868,  0.90597002, -0.82719391, -0.04691282,
        0.21222789,  0.95308316,  0.12231401,  0.45857881, -0.91727347,
       -0.61379784,  0.70786907,  0.5156301 ,  0.30850097, -0.22453886,
        0.27860628,  0.19003622,  0.22636302, -0.84828504,  0.2771514 ,
       -0.8380968 ,  0.09067254,  0.6627017 , -0.03299432, -0.94513417,
       -0.78063842,  0.35328157,  0.22828475,  0.99191444, -0.04161815,
        0.190932  , -0.34335028,  0.89178611,  0.26676662, -0.11258393,
       -0.03322054,  0.8206834 , -0.05011197, -0.77471117, -0.48128028,
       -0.65340121, -0.72215699, -0.38552687, -0.01889977, -0.65525032,
        0.70369293, -0.82070123, -0.82761877,  0.65449578,  0.37784124,
        0.41465601,  0.9064556 , -0.2088198 ,  0.92793127, -0.64

In [22]:
# Consider 2 sets of points P0,P1 describing lines (2d) and a point p,
# how to compute distance from p to each line i (P0[i],P1[i])

def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[13.20862198  3.85773518 12.85276382 12.40202617  6.94093977 12.89375912
  9.87379588  1.27408593  4.13452323  0.59941586]


In [23]:
# Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P,
# how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i]

P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 3.65797249  7.66446131  2.09318406 11.2843245   9.09621876 14.73115589
   0.99949153 16.75004409  0.4929382   0.33708247]
 [ 0.66937929  2.09392552  8.04696437  4.39482161  5.76871922  4.56736832
   3.21622547  7.37951707  0.66980027  5.30661064]
 [ 3.68611657  7.9336655   2.46354144 11.47071596  9.13742849 15.09898322
   0.83913533 17.11856396  0.61691054  0.23093607]
 [ 4.19037463  6.93917603 15.87847208  3.76822602  8.97850017  3.0382208
  10.64098424  1.74800521  7.43250914  3.7221583 ]
 [ 0.08953157  0.76535099 12.45403071  1.83539244  4.85793198  0.17264698
   4.70884361  3.13182381  1.71841397  6.96413291]
 [ 5.71199895  3.40829314  9.8347202   7.66542543 10.70432354  3.00874444
   9.06530582  3.92123828  6.47826578  1.00174167]
 [ 2.32839209  1.58995874 11.77138821  0.3341707   2.66259389  0.75467035
   2.16830174  4.55397102  0.81478964  8.89942914]
 [ 7.57173738  2.75513962 15.6902356   5.62083899  2.67703312  3.34456811
   0.98167549  2.25842012  4.47869496 14.6231602 ]
 

In [25]:
# Consider an arbitrary array,
# write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]

print(Z)
print(R)

[[4 7 8 2 4 1 6 8 4 0]
 [9 5 4 8 9 6 2 3 7 5]
 [1 9 3 3 8 4 7 5 7 8]
 [1 2 3 5 5 7 0 9 7 7]
 [4 2 8 8 5 3 0 5 0 5]
 [0 0 1 7 6 1 7 7 5 3]
 [6 6 5 2 0 6 7 4 9 1]
 [3 5 3 7 3 5 7 7 9 2]
 [4 0 3 8 2 6 3 8 5 6]
 [2 2 4 0 4 4 2 3 1 9]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [26]:
#  Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]

Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [27]:
# Compute a matrix rank

Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


In [28]:
# How to find the most frequent value in an array

Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

3


In [30]:
# Extract all the contiguous 3x3 blocks from a random 10x10 matrix

Z = np.random.randint(0,5,(10,10))
print(sliding_window_view(Z, window_shape=(3, 3)))

[[[[2 0 0]
   [4 1 4]
   [1 1 1]]

  [[0 0 1]
   [1 4 1]
   [1 1 3]]

  [[0 1 3]
   [4 1 0]
   [1 3 3]]

  [[1 3 2]
   [1 0 2]
   [3 3 2]]

  [[3 2 4]
   [0 2 4]
   [3 2 2]]

  [[2 4 3]
   [2 4 1]
   [2 2 3]]

  [[4 3 0]
   [4 1 3]
   [2 3 0]]

  [[3 0 1]
   [1 3 2]
   [3 0 1]]]


 [[[4 1 4]
   [1 1 1]
   [2 0 3]]

  [[1 4 1]
   [1 1 3]
   [0 3 1]]

  [[4 1 0]
   [1 3 3]
   [3 1 0]]

  [[1 0 2]
   [3 3 2]
   [1 0 0]]

  [[0 2 4]
   [3 2 2]
   [0 0 4]]

  [[2 4 1]
   [2 2 3]
   [0 4 2]]

  [[4 1 3]
   [2 3 0]
   [4 2 0]]

  [[1 3 2]
   [3 0 1]
   [2 0 4]]]


 [[[1 1 1]
   [2 0 3]
   [4 0 1]]

  [[1 1 3]
   [0 3 1]
   [0 1 0]]

  [[1 3 3]
   [3 1 0]
   [1 0 4]]

  [[3 3 2]
   [1 0 0]
   [0 4 1]]

  [[3 2 2]
   [0 0 4]
   [4 1 0]]

  [[2 2 3]
   [0 4 2]
   [1 0 1]]

  [[2 3 0]
   [4 2 0]
   [0 1 1]]

  [[3 0 1]
   [2 0 4]
   [1 1 1]]]


 [[[2 0 3]
   [4 0 1]
   [0 4 2]]

  [[0 3 1]
   [0 1 0]
   [4 2 2]]

  [[3 1 0]
   [1 0 4]
   [2 2 0]]

  [[1 0 0]
   [0 4 1]
   [2 0 0]]

  [[0 0 4]
   

In [31]:
# Create a 2D array subclass such that Z[i,j] == Z[j,i]

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 3  5  4  9 12]
 [ 5  1  6 16 11]
 [ 4  6  2 42  5]
 [ 9 16 42  1  8]
 [12 11  5  8  4]]


In [32]:
# Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1).
# How to compute the sum of of the p matrix products at once? (result has shape (n,1))

p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [34]:
# Consider a 16x16 array, how to get the block-sum (block size is 4x4)

Z = np.ones((16,16))
k = 4

windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [35]:
# How to implement the Game of Life using numpy arrays

def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 0 0 0]]


In [36]:
# How to get the n largest values of an array

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argpartition(-Z,n)[:n]])

[9997 9999 9998 9996 9995]


In [37]:
# Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)

def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [38]:
# How to create a record array from a regular array

Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [39]:
# Consider a large vector Z, compute Z to the power of 3 using 3 different methods

x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1.54 s ± 193 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
265 ms ± 22 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
190 ms ± 4.13 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [40]:
# Consider two arrays A and B of shape (8,3) and (2,2).
# How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[2 6]


In [41]:
# Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[3 4 1]
 [0 1 1]
 [2 1 4]
 [4 4 1]
 [2 0 2]
 [0 3 3]
 [3 3 0]
 [3 0 0]
 [4 1 1]
 [1 1 4]]
[[3 4 1]
 [0 1 1]
 [2 1 4]
 [4 4 1]
 [2 0 2]
 [0 3 3]
 [3 3 0]
 [3 0 0]
 [4 1 1]
 [1 1 4]]
[[3 4 1]
 [0 1 1]
 [2 1 4]
 [4 4 1]
 [2 0 2]
 [0 3 3]
 [3 3 0]
 [3 0 0]
 [4 1 1]
 [1 1 4]]


In [42]:
# Convert a vector of ints into a matrix binary representation

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [43]:
# Given a two dimensional array, how to extract unique rows

Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 1]
 [1 1 0]
 [1 1 1]]


In [44]:
# Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.3699828 , 0.3606179 , 0.33614445, 0.49517135, 0.0368241 ,
        0.25918877, 0.24029716, 0.51427729, 0.3853674 , 0.37990008],
       [0.61235761, 0.59685778, 0.55635184, 0.81955686, 0.06094747,
        0.42898268, 0.39771522, 0.85117905, 0.63782062, 0.62877168],
       [0.00889061, 0.00866557, 0.00807748, 0.01189886, 0.00088488,
        0.00622825, 0.00577429, 0.01235797, 0.00926029, 0.00912892],
       [0.20638408, 0.20116014, 0.18750835, 0.27621685, 0.02054125,
        0.14458087, 0.13404274, 0.28687454, 0.21496593, 0.21191615],
       [0.19353067, 0.18863208, 0.1758305 , 0.25901433, 0.01926196,
        0.13557651, 0.12569468, 0.26900826, 0.20157805, 0.19871821],
       [0.36633437, 0.35706182, 0.3328297 , 0.49028843, 0.03646097,
        0.25663288, 0.23792757, 0.50920596, 0.38156726, 0.37615386],
       [0.15082053, 0.14700301, 0.1370266 , 0.20185265, 0.01501105,
        0.10565623, 0.09795522, 0.20964103, 0.15709194, 0.15486324],
       [0.04399032, 0.04287685, 0.039967 

In [46]:
# Considering a path described by two vectors (X,Y), how to sample it using equidistant samples

phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)
print(dr)

[0.1        0.10099422 0.10295387 0.10582533 0.10953691 0.11400658
 0.11914907 0.12488128 0.1311259  0.13781329 0.14488215 0.15227936
 0.15995938 0.16788341 0.17601848 0.18433667 0.19281427 0.20143115
 0.21017019 0.21901677 0.22795836 0.2369842  0.24608504 0.25525285
 0.26448065 0.2737624  0.28309278 0.29246713 0.30188136 0.31133186
 0.32081541 0.33032917 0.33987061 0.34943745 0.35902767 0.36863944
 0.37827112 0.38792122 0.39758841 0.40727146 0.41696928 0.42668085
 0.43640526 0.44614167 0.4558893  0.46564746 0.4754155  0.48519281
 0.49497885 0.50477312 0.51457514 0.52438447 0.53420072 0.54402351
 0.55385249 0.56368734 0.57352776 0.58337346 0.59322418 0.60307968
 0.61293972 0.62280409 0.63267259 0.64254503 0.65242122 0.662301
 0.67218422 0.68207071 0.69196035 0.701853   0.71174853 0.72164683
 0.73154777 0.74145127 0.75135721 0.7612655  0.77117605 0.78108877
 0.79100358 0.80092041 0.81083918 0.82075982 0.83068226 0.84060644
 0.8505323  0.86045978 0.87038883 0.88031938 0.8902514  0.900184

In [47]:
# Given an integer n and a 2D array X,
# select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees,
# i.e., the rows which only contain integers and which sum to n

X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [48]:
# Compute bootstrapped 95% confidence intervals for the mean of a 1D array X
# (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means)

X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.00454004  0.36162019]
