<a href="https://colab.research.google.com/github/Desmyk/PYDATA/blob/main/numpytest2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [35]:
# How to add a border (filled with 0's) around an existing array?

a = np.random.random((4, 5))
m, n = a.shape
b = np.pad(a, 1)
print(b)

[[0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.55358663 0.58992626 0.56954343 0.03184257 0.65613241
  0.        ]
 [0.         0.76057462 0.02281701 0.72551675 0.54887231 0.5771922
  0.        ]
 [0.         0.65051388 0.99998735 0.97241665 0.16600436 0.19220841
  0.        ]
 [0.         0.64822317 0.02709501 0.2991171  0.96847536 0.68397013
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.        ]]


In [27]:
 # What is the result of the following expression?

 0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [36]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

X = np.diag([1, 2, 3, 4, 5])
print(X)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [10]:
# Create a 8x8 matrix and fill it with a checkerboard pattern

X = np.zeros((8,8),dtype=int)
X[1::2,::2]=1
X[::2,1::2]=1
print(X)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [5]:
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [26]:
 # Create a checkerboard 8x8 matrix using the tile function
X = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(X)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [13]:
# Normalize a 5x5 random matrix

X = np.random.random((5,5))
Xmax,Xmin=X.max(),X.min()
X =(X-Xmin)/(Xmax-Xmin)
print(X)


[[0.39564844 0.93548549 0.85144663 0.4484104  1.        ]
 [0.28359181 0.71955673 0.         0.66314439 0.13054192]
 [0.82423059 0.48872546 0.77967593 0.55965352 0.55508624]
 [0.64952212 0.33282046 0.48129014 0.82285786 0.59746363]
 [0.98064425 0.2748113  0.15852098 0.1033447  0.02979015]]


In [7]:
# Create a custom dtype that describes a color as four unsigned bytes (RGBA)

color=np.dtype([("r",np.ubyte,1),
                ("g",np.ubyte,1),
                ("b",np.ubyte,1),
                ("a",np.ubyte,1)])

<ipython-input-7-f54b7ee2ad8e>:3: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color=np.dtype([("r",np.ubyte,1),


In [9]:
# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

X = np.dot(np.ones((5,3)),np.ones((3,2)))
print(X)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [16]:
# Given a 1D array, negate all elements which are between 3 and 8, in place

X = np.arange(11)
X[(3<X)&(X<=8)]*=-1
print(X)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [25]:
# What is the output of the following script?
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [32]:
#  Consider an integer vector Z, which of these expressions are legal?

#This code has no syntax errors.
[1j*X]
[X/1/1]



[array([[0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.]])]

In [29]:
#  What are the result of the following expressions?
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-29-4d15ae8654db>:2: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-29-4d15ae8654db>:3: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-29-4d15ae8654db>:4: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

In [17]:
# How to round away from zero a float array

X = np.random.uniform(-10,+10,10)
print(np.trunc(X + np.copysign(0.5,X)))

[  3.   7.  -6.  -1.   3.   9. -10.   5.  -6.  -0.]


In [22]:
# How to find common values between two arrays
ar1 = [0,1,2,3,4,5,8,7]
ar2 = [1,3,15,7,10]
print(np.intersect1d(ar1, ar2))

[1 3 7]
